name: Pull Request

on:
  pull_request:
    branches: [development, staging]

jobs:
  build:
    name: Test if project builds
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow runs on pull requests."

      - name: echo secret
        run: echo "secret ${{ secrets.FIRST_GITHUB_SECRET }}"
